### ISSUE TITLE
netcdf build fails with autoconf due to CC=gcc override

### ISSUE THREAD

**Issue by physicalist** [borismarin/genesis2.4gamma#16]
Boris was right, netcdf fails to compile using gcc. More exactly, netcdf's configure script fails at the fruncate() test with the following error:

```
checking whether cross-compiling... yes
checking for working ftruncate()... configure: error: can not run test program while cross compiling
Makefile:15: macros.make: No such file or directory
Makefile:179: warning: overriding commands for target `/netcdf-.tar.Z'
Makefile:165: warning: ignoring old commands for target `/netcdf-.tar.Z'
rules.make:120: warning: overriding commands for target `/'
rules.make:118: warning: ignoring old commands for target `/'
rules.make:122: warning: overriding commands for target `/'
rules.make:120: warning: ignoring old commands for target `/'
rules.make:125: warning: overriding commands for target `/'
rules.make:122: warning: ignoring old commands for target `/'
rules.make:128: warning: overriding commands for target `/'
rules.make:125: warning: ignoring old commands for target `/'
rules.make:142: warning: overriding commands for target `/man1'
rules.make:139: warning: ignoring old commands for target `/man1'
rules.make:144: warning: overriding commands for target `/man3'
rules.make:139: warning: ignoring old commands for target `/man3'
rules.make:147: warning: overriding commands for target `/man3f'
rules.make:139: warning: ignoring old commands for target `/man3f'
rules.make:152: warning: overriding commands for target `/'
rules.make:128: warning: ignoring old commands for target `/'
make[5]: *** No rule to make target `macros.make'.  Stop.
make[4]: *** [netcdflib] Error 2
```

I don't know why this happens, or why configure thinks I'm cross-compiling. More interestingly, if I force the compiler to be clang using `CC=cc CPP=cpp ./configure && make`, the error still appears.
What's even more weird, when I tried `./configure && CC=cc CPP=cpp make`, the `*/*@.c` files would be messed up and compilation failed due to that.

netcdflib seems to be much more hassle than it's worth, really.

However, when I'm _not_ using autoconf but simply the 2.4beta codebase with minimal changes, it compiles fine using cc!

**Comment by physicalist** [comment]
I think I got it! The issue seems to be the line
`LIBS=$(LEXLIB) -lm @X_PRE_LIBS@` in Makefile.in,
or rather the `@X_PRE_LIBS@` directive, which in my case is replaced with `-lSM -lICE`. If I comment those two out then everything compiles fine (using gcc)!
I'm now testing if `CC=cc CPP=cpp ./configure && make` also works, i.e. using clang instead.

**Comment by physicalist** [comment]
Yes it does. So I can confirm that GENESIS 2.4 final beta builds using autoconf on MacOS X 10.9.5 with both clang and gcc (the latter Apple's bundled version).
It also builds with gcc-4.9 from homebrew.

CONFIRMED: `-lSM -lICE` in `LIBS` breaks compatibility with netcdf on (at least) MacOS X 10.9+
I tested each with different compilers, to no avail. netcdf always fails at the ftruncate() test.
SOLVED with ce9af997d3d345a98ae1c8ca078fe1034fae5b34

**Comment by physicalist** [comment]
Please check if this works on Linux systems as well...

**Comment by borismarin** [comment]
Works on linux (locally), and travis workers as well (see #21).
